export const types = {
    SET_PLAYER_ORDER: 'SET_PLAYER_ORDER',
    ROUND_NUMBER_CHANGED: 'ROUND_NUMBER_CHANGED',
    SET_GAME_STEP: 'SET_GAME_STEP',
    SET_SELECTION_ITEM: 'SET_SELECTION_ITEM',
    SET_ROUND_CHANGE: 'SET_ROUND_CHANGE'
}