export const types = {
    FIRST_PLAYER_HIT: 'FIRST_PLAYER_HIT',
    SECOND_PLAYER_HIT: 'SECOND_PLAYER_HIT',
    FIRST_PLAYER_ADD_ITEM: 'FIRST_PLAYER_ADD_ITEM',
    SECOND_PLAYER_ADD_ITEM: 'SECOND_PLAYER_ADD_ITEM'
}